### ISSUE TITLE
json-ld 1.1 preprocessing checklist

### ISSUE THREAD

**Issue by dbooth-boston** [fhircat/FHIRCat#2]
We might want to break this into separate issues, but I thought I would experiment with github's new-ish checklist feature.  

These are known issues that we'll need to address in a JSON preprocessor.  Please add to these if you think of more.

- [ ] Map fhir:valueX properties to RDF datatypes.  See slide 5: https://lists.w3.org/Archives/Public/www-archive/2019Nov/att-0000/FHIRRdf.pdf
- [ ] Connect FHIR extension element "_foo" to element "foo", so that an RDF query can traverse from any element ?foo to its extensions, without hard-coding the element names.  See slide 12: https://lists.w3.org/Archives/Public/www-archive/2019Nov/att-0000/FHIRRdf.pdf
- [ ] Runtime type determination from union types.  fhir:valueDate and valueDateTime (any others?) require runtime inspection of the value in order to determine the specific RDF type that was used.
- [ ] Retain significant digits in decimals, such as "1.000" versus "1.0".
- [ ] Add fhir:nodeRole fhir:treeRoot .  See https://www.hl7.org/fhir/rdf.html
- [ ] Add fhir:id elements that were removed by @id conversion to URIs.  This is needed because when the FHIR/JSON says `"id": "abc123"` an `@id` in the `@context` will (hopefullly) convert it to be the URI of the element, which means that the "id" string property is lost.  Preprocessing can put it back in.
- [ ] Add fhir:link properties.  See https://www.hl7.org/fhir/rdf.html
- [ ] Add types of Concept references.  See https://www.hl7.org/fhir/rdf.html#concept

**Comment by dbooth-boston** [comment]
I added the R5 label because some of these items are relevant to R5.
